
Metrics/AbcSize:
  Enabled: false
  
EndOfLine:
  Enabled: false
  
AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'db/migrate/**/*'
  SuggestExtensions: false
  NewCops: disable

Style/FrozenStringLiteralComment:
  Enabled: false

Style/BlockComments:
  Enabled: false

Metrics/LineLength:
  Description: 'Limit lines to 80 characters.'
  StyleGuide: '#80-character-limits'
  Enabled: false

Style/MixinUsage:
  Description: 'Use `include` (or `extend`, `prepend`) instead of `Object#extend`.'
  Enabled: false

Style/StringLiterals:
  Description: 'Checks if uses of quotes match the configured preference.'
  StyleGuide: '#consistent-string-literals'
  Enabled: false

Metrics/BlockLength:
  Description: 'Avoid long blocks with many lines.'
  Enabled: false

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false